# Generated by Django 5.1.15 on 2026-08-06 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterProfile',
            fields=[
                ('shelter_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=150)),
                ('org_type', models.CharField(choices=[('shelter', 'Shelter'), ('rescue', 'Rescue'), ('pound', 'Pound')], max_length=20)),
                ('tier', models.CharField(choices=[('community_rescue', 'Community Rescue'), ('registered_ngo', 'Registered Ngo')], default='community_rescue', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.TextField(blank=True)),
                ('registration_type', models.CharField(blank=True, choices=[('SEC', 'Sec'), ('DTI', 'Dti'), ('BIR', 'Bir')], max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('contact_person_name', models.CharField(blank=True, max_length=100)),
                ('contact_person_role', models.CharField(blank=True, max_length=60)),
                ('official_email', models.CharField(blank=True, max_length=254)),
                ('official_phone', models.CharField(blank=True, max_length=20)),
                ('website_url', models.TextField(blank=True)),
                ('vet_name', models.CharField(blank=True, max_length=120)),
                ('vet_prc_number', models.CharField(blank=True, max_length=30)),
                ('is_escalation_partner', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to='accounts.account')),
            ],
            options={
                'db_table': 'shelter_profile',
            },
        ),
    ]
