# Generated by Django 5.1.15 on 2026-08-19 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationQr',
            fields=[
                ('donation_qr_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gcash', 'Gcash'), ('maya', 'Maya')], max_length=10)),
                ('account_name', models.CharField(max_length=120)),
                ('qr_image_url', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_qrs', to='accounts.account')),
            ],
            options={
                'db_table': 'donation_qr',
                'indexes': [models.Index(fields=['account'], name='idx_donation_qr_account')],
            },
        ),
    ]
