# Generated by Django 5.1.15 on 2026-08-03 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionListing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(max_length=20)),
                ('breed', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('listing_status', models.CharField(default='available', max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.account')),
            ],
            options={
                'db_table': 'adoption_listing',
            },
        ),
    ]
