# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_deleted_at_account_last_active_at_and_more'),
        ('listings', '0003_adoption_inquiry_decided_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionlisting',
            name='posted_by',
            field=models.ForeignKey(db_column='posted_by_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.account'),
        ),
    ]
