# Generated by Django 5.1.15 on 2026-09-02 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterNeed',
            fields=[
                ('need_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('food', 'Food'), ('medicine', 'Medicine'), ('supplies', 'Supplies'), ('funds', 'Funds'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('quantity_needed', models.IntegerField(default=1)),
                ('quantity_received', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_needs', to='accounts.account')),
            ],
            options={
                'db_table': 'shelter_need',
            },
        ),
        migrations.CreateModel(
            name='NeedPledge',
            fields=[
                ('pledge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pledged', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='need_pledges', to='accounts.account')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='community.shelterneed')),
            ],
            options={
                'db_table': 'need_pledge',
            },
        ),
        migrations.AddIndex(
            model_name='shelterneed',
            index=models.Index(fields=['shelter_account', 'status'], name='idx_shelter_need_shelter'),
        ),
        migrations.AddIndex(
            model_name='shelterneed',
            index=models.Index(fields=['category'], name='idx_shelter_need_category'),
        ),
        migrations.AddConstraint(
            model_name='shelterneed',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_needed__gte', 1)), name='shelter_need_needed_min1'),
        ),
        migrations.AddConstraint(
            model_name='shelterneed',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='shelter_need_received_min0'),
        ),
        migrations.AddIndex(
            model_name='needpledge',
            index=models.Index(fields=['need'], name='idx_need_pledge_need'),
        ),
        migrations.AddIndex(
            model_name='needpledge',
            index=models.Index(fields=['pledger_account'], name='idx_need_pledge_pledger'),
        ),
        migrations.AddConstraint(
            model_name='needpledge',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='need_pledge_quantity_min1'),
        ),
    ]
