# Generated by Django 5.1.15 on 2026-09-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True)),
                ('criteria', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'badge',
            },
        ),
        migrations.CreateModel(
            name='AccountBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.account')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community.badge')),
            ],
            options={
                'db_table': 'account_badge',
                'constraints': [models.UniqueConstraint(fields=('account', 'badge'), name='uq_account_badge')],
            },
        ),
    ]
