# Generated by Django 5.1.15 on 2026-09-02 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('community', '0003_seed_badges'),
        ('listings', '0003_adoption_inquiry_decided_at'),
        ('sagip', '0005_strayreport_breed_strayreport_color_markings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('story_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_type', models.CharField(choices=[('adoption', 'Adoption'), ('rescue', 'Rescue'), ('general', 'General')], max_length=10)),
                ('caption', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adoption_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listings.adoptionlisting')),
                ('author_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='accounts.account')),
                ('rescue_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sagip.rescuecase')),
            ],
            options={
                'db_table': 'story_post',
            },
        ),
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='community.storypost')),
            ],
            options={
                'db_table': 'story_photo',
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to='accounts.account')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.storypost')),
            ],
            options={
                'db_table': 'story_reaction',
            },
        ),
        migrations.AddIndex(
            model_name='storypost',
            index=models.Index(fields=['author_account'], name='idx_story_post_author'),
        ),
        migrations.AddIndex(
            model_name='storypost',
            index=models.Index(fields=['status', '-created_at'], name='idx_story_post_status'),
        ),
        migrations.AddIndex(
            model_name='storyreaction',
            index=models.Index(fields=['account'], name='idx_story_reaction_account'),
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(fields=('story', 'account'), name='uq_story_reaction'),
        ),
    ]
