# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_storypost_storyphoto_storyreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbadge',
            name='badge',
            field=models.ForeignKey(db_column='badge_code', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community.badge'),
        ),
    ]
