# Generated by Django 5.1.15 on 2026-08-03 14:24

import accounts.models
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('shelter', 'Shelter'), ('admin', 'Admin')], max_length=20)),
                ('email', accounts.models.CICharField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.TextField(blank=True)),
                ('display_name', models.CharField(max_length=100)),
                ('photo_url', models.TextField(blank=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('settings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('approximate_location', models.BooleanField(default=True)),
                ('masked_contact', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.account')),
            ],
            options={
                'db_table': 'account_settings',
            },
        ),
    ]
