# Generated by Django 5.1.15 on 2026-08-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sessions_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
