# Generated by Django 5.1.15 on 2026-08-03 15:38

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_sessions_revoked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIdentity',
            fields=[
                ('identity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=10)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', accounts.models.CICharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='accounts.account')),
            ],
            options={
                'db_table': 'account_identity',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uq_provider_sub'), models.UniqueConstraint(fields=('account', 'provider'), name='uq_account_provider')],
            },
        ),
    ]
