# Generated by Django 5.1.15 on 2026-08-03 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """`geom` is `geography(Point,4326)` in `kupkop_mvp_schema.sql`; modeled as
    nullable text here because Journey A stores no person coordinate
    (decision 11) and this slice avoids a PostGIS dependency. Reconcile to
    PostGIS when shelter addresses land."""

    dependencies = [
        ('accounts', '0003_accountidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('line1', models.TextField(blank=True)),
                ('barangay', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('geom', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.account')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
