# Generated by Django 5.1.15 on 2026-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='terms_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='terms_consent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
