# Generated by Django 5.1.15 on 2026-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('status', 'deleted')), models.Q(('deleted_at__isnull', True), models.Q(('status', 'deleted'), _negated=True)), _connector='OR'), name='chk_account_deleted_consistency'),
        ),
    ]
