# Generated by Django 5.1.15 on 2026-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_deleted_at_account_last_active_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='analytics_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='analytics_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
