# Generated by Django 5.1.15 on 2026-09-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountsettings_analytics_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
