# Generated by Django 5.1.15 on 2026-08-12 12:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('sagip', '0001_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrayReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('stray', 'Stray'), ('lost', 'Lost'), ('found', 'Found')], default='stray', max_length=10)),
                ('pet_id', models.UUIDField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('condition', models.CharField(choices=[('injured', 'Injured'), ('sick', 'Sick'), ('healthy', 'Healthy'), ('pregnant', 'Pregnant')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('claimed', 'Claimed'), ('rescued', 'Rescued'), ('safe', 'Safe'), ('resolved', 'Resolved')], default='reported', max_length=10)),
                ('escalation_level', models.SmallIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('barangay', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stray_reports', to='accounts.account')),
            ],
            options={
                'db_table': 'stray_report',
            },
        ),
        migrations.CreateModel(
            name='StrayReportPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sagip.strayreport')),
            ],
            options={
                'db_table': 'stray_report_photo',
            },
        ),
    ]
