# Generated by Django 5.1.15 on 2026-08-19 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('sagip', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('claimed', 'Claimed'), ('rescued', 'Rescued'), ('safe', 'Safe'), ('resolved', 'Resolved')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sagip.strayreport')),
            ],
            options={
                'db_table': 'case_status_history',
                'indexes': [models.Index(fields=['report', '-changed_at'], name='idx_case_history_report')],
            },
        ),
        migrations.CreateModel(
            name='RescueCase',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('outcome_photo_url', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_cases', to='accounts.account')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='sagip.strayreport')),
            ],
            options={
                'db_table': 'rescue_case',
                'constraints': [models.UniqueConstraint(condition=models.Q(('expired_at__isnull', True)), fields=('report',), name='idx_rescue_case_active')],
            },
        ),
    ]
