# Generated by Django 5.1.15 on 2026-08-23 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('sagip', '0003_casestatushistory_rescuecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOffer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('transport', 'Transport'), ('vet_costs', 'Vet Costs'), ('supplies', 'Supplies')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('expired', 'Expired')], default='open', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_offers', to='accounts.account')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sagip.strayreport')),
            ],
            options={
                'db_table': 'report_offer',
                'indexes': [models.Index(fields=['report', 'status'], name='idx_report_offer_report'), models.Index(fields=['account', '-created_at'], name='idx_report_offer_account')],
                'constraints': [models.UniqueConstraint(fields=('report', 'account', 'offer_type'), name='uq_report_offer_type')],
            },
        ),
    ]
