# Generated by Django 5.1.15 on 2026-09-02 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagip', '0004_reportoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayreport',
            name='breed',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='color_markings',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='size_category',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ReportMatch',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='suggested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sagip.strayreport')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sagip.strayreport')),
            ],
            options={
                'db_table': 'report_match',
                'indexes': [models.Index(fields=['matched_report'], name='idx_report_match_matched'), models.Index(fields=['status'], name='idx_report_match_status')],
                'constraints': [models.UniqueConstraint(fields=('report', 'matched_report'), name='idx_report_match_pair'), models.CheckConstraint(condition=models.Q(('report', models.F('matched_report')), _negated=True), name='report_match_not_self')],
            },
        ),
    ]
