# Generated by Django 5.2.17 on 2026-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_anonymized_at'),
        ('sagip', '0005_strayreport_breed_strayreport_color_markings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayreport',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='strayreport',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('reporter_account', 'idempotency_key'), name='idx_stray_report_idempotency'),
        ),
    ]
