# Generated by Django 5.1.15 on 2026-08-24 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('listings', '0002_adoption_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerShift',
            fields=[
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('walking', 'Walking'), ('feeding', 'Feeding'), ('visitor', 'Visitor'), ('event', 'Event'), ('facility', 'Facility'), ('transport', 'Transport')], default='walking', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_shifts', to='accounts.account')),
            ],
            options={
                'db_table': 'volunteer_shift',
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignup',
            fields=[
                ('signup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='requested', max_length=10)),
                ('waiver_accepted', models.BooleanField(default=False)),
                ('waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_version', models.CharField(blank=True, max_length=20)),
                ('contact_share_consent', models.BooleanField(default=False)),
                ('contact_share_consent_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listings.adoptionlisting')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='volunteer.volunteershift')),
                ('volunteer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_signups', to='accounts.account')),
            ],
            options={
                'db_table': 'volunteer_signup',
            },
        ),
        migrations.AddIndex(
            model_name='volunteershift',
            index=models.Index(fields=['shelter_account', 'starts_at'], name='idx_volunteer_shift_shelter'),
        ),
        migrations.AddIndex(
            model_name='volunteershift',
            index=models.Index(fields=['status'], name='idx_volunteer_shift_status'),
        ),
        migrations.AddConstraint(
            model_name='volunteershift',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='volunteer_shift_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='volunteershift',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='volunteer_shift_capacity_min1'),
        ),
        migrations.AddIndex(
            model_name='volunteersignup',
            index=models.Index(fields=['volunteer_account'], name='idx_volunteer_signup_walker'),
        ),
        migrations.AddIndex(
            model_name='volunteersignup',
            index=models.Index(fields=['status'], name='idx_volunteer_signup_status'),
        ),
        migrations.AddConstraint(
            model_name='volunteersignup',
            constraint=models.UniqueConstraint(fields=('shift', 'volunteer_account'), name='idx_volunteer_signup_pair'),
        ),
    ]
