# Generated by Django 5.1.15 on 2026-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('listings', '0002_adoption_module'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='volunteersignup',
            index=models.Index(fields=['assigned_listing'], name='idx_volunteer_signup_listing'),
        ),
    ]
