# Generated by Django 5.1.15 on 2026-08-24 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('flag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('account', 'Account'), ('listing', 'Listing'), ('report', 'Report'), ('qr', 'Qr'), ('message', 'Message')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_flags_raised', to='accounts.account')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
            ],
            options={
                'db_table': 'moderation_flag',
                'indexes': [models.Index(fields=['status'], name='idx_flag_status'), models.Index(fields=['target_type', 'target_id'], name='idx_flag_target')],
            },
        ),
    ]
