# Generated by Django 5.1.15 on 2026-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationflag',
            name='target_type',
            field=models.CharField(choices=[('account', 'Account'), ('listing', 'Listing'), ('report', 'Report'), ('qr', 'Qr'), ('message', 'Message'), ('story', 'Story')], max_length=10),
        ),
    ]
