# Generated by Django 5.1.15 on 2026-08-03 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms')], max_length=10)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('phone', 'Phone'), ('reset', 'Reset')], max_length=10)),
                ('code_hash', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='accounts.account')),
            ],
            options={
                'db_table': 'verification_code',
                'indexes': [models.Index(fields=['account', 'purpose', '-created_at'], name='verificatio_account_dda1e4_idx')],
            },
        ),
    ]
