# Generated by Django 5.1.15 on 2026-08-03 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('shelter_org', 'Shelter Org'), ('rescuer', 'Rescuer'), ('provider', 'Provider')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('needs_info', 'Needs Info'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('social_proof_url', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.account')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
            ],
            options={
                'db_table': 'verification_request',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=30)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verifications.verificationrequest')),
            ],
            options={
                'db_table': 'verification_document',
            },
        ),
        migrations.CreateModel(
            name='AccountCapability',
            fields=[
                ('capability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('rescuer', 'Rescuer'), ('provider', 'Provider')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='accounts.account')),
            ],
            options={
                'db_table': 'account_capability',
                'constraints': [models.UniqueConstraint(fields=('account', 'capability'), name='uq_account_capability')],
            },
        ),
    ]
