# Generated by Django 5.1.15 on 2026-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
        ('verifications', '0002_verificationrequest_verificationdocument_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['account', 'type', 'status'], name='idx_verification_acct_type_st'),
        ),
    ]
