# Generated by Django 5.1.15 on 2026-08-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('verifications', '0003_verificationrequest_idx_verification_acct_type_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verifications.verificationdocument'),
        ),
    ]
