# Generated by Django 5.1.15 on 2026-08-24 00:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('verifications', '0004_verificationdocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAccessLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_username', models.CharField(max_length=150)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='verifications.verificationrequest')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
            ],
            options={
                'db_table': 'verification_access_log',
                'indexes': [models.Index(fields=['verification', '-viewed_at'], name='verificatio_verific_b02fe4_idx')],
            },
        ),
    ]
