# Generated by Django 5.1.15 on 2026-08-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0005_verificationaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
