# Generated by Django 5.1.15 on 2026-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_deleted_at_account_last_active_at_and_more'),
        ('verifications', '0006_verificationdocument_purged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationaccesslog',
            name='viewer',
            field=models.ForeignKey(blank=True, db_column='viewer_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, db_column='superseded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verifications.verificationdocument'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
    ]
