# Generated by Django 5.1.15 on 2026-08-12 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['account', 'read', '-created_at'], name='idx_notification_account')],
            },
        ),
    ]
